### ISSUE TITLE
EventProfiler example does not work

### ISSUE THREAD

**Issue by Elijen** [QuantSoftware/QuantSoftwareToolkit#66]
`Examples/EventProfiler/tutorial.py` does not seem to produce expected result.

The following warning is produced:

```
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/QSTK/qstkutil/qsdateutil.py:36: FutureWarning: TimeSeries is deprecated. Please use Series
  return pd.TimeSeries(index=dates, data=dates)
```

The generated PDF graph is blank
[MyEventStudy.pdf](https://github.com/QuantSoftware/QuantSoftwareToolkit/files/76759/MyEventStudy.pdf)

This is the output of `pip list`

```
cycler (0.9.0)
matplotlib (1.5.0)
nose (1.3.7)
numpy (1.10.1)
pandas (0.17.1)
pip (7.1.0)
pyparsing (2.0.6)
python-dateutil (1.5)
pytz (2015.7)
QSTK (0.2.8)
scikit-learn (0.17)
scikits.statsmodels (0.3.1)
scipy (0.16.1)
setuptools (18.0.1)
six (1.10.0)
wheel (0.24.0)
```

**Comment by sg2013test** [comment]
I have the same problem

**Comment by allen-ng** [comment]
Hey I found the same problem for event profiling.
It seems that something inside the event profiler about indexing data has gone wrong.
Tryin' to fix this

**Comment by 12379Monty** [comment]
I ran into this problem as well while trying to work through some Coursera homework.  Is there a way to alert someone who can help resolve this issue?

**Comment by CaryLorrk** [comment]
reference to pull request  #69

**Comment by emma11235** [comment]
Awesome! This quick fix worked for me as well! Been frustrated yesterday when got an empty plot. Thank you!!!
Strange it's working for others, including the instructor on video (Coursera)

**Comment by Elijen** [comment]
Make sure you install the exact versions of dependencies specified in README. There were some BC breaks introduced in newer versions.
